version: '3'
services:
    php70-first:
      build:
        context: ./images/php70
        args:
          - USER_ID
          - GROUP_ID
      volumes:
        - ./www:/var/www
        - ./aliases/php70/bash.bashrc:/etc/bash.bashrc
      #environment:
      #  XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1 remote_autostart=off  remote_port=9008"
      #  PHP_IDE_CONFIG: "serverName=first"
      networks:
        - server-70-maria5
    nginx-test:
      image: nginx
      volumes:
        - ./hosts:/etc/nginx/conf.d
        - ./www:/var/www
        - ./logs:/var/log/nginx
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php70-first
      networks:
        server-70-maria5:
          aliases: # алиасы нужны если нужно общаться внутри сети между хостами. Например, если вы используете api
            - magizoo.loc
            - magizoo-red.loc
    mysql:
      image: mariadb:5.5
      ports:
        - "3306:3306"
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./my.cnf:/etc/mysql/my.cnf
      environment:
        MYSQL_ROOT_PASSWORD: secret
      networks:
        - server-70-maria5
networks:
  server-70-maria5:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/28
